# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: '0 0 * * *' }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'Kshao123/metrics'
          fetch-depth: 0
          ref: ${{ github.ref }}
          path: 'metrics'

      - name: checkout path
        run: |
          ls
          cd ./metrics
        
      - name: 🐈‍⬛ Left
        uses: ./
        with:
          filename: assets/left.svg
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, starts, achievements
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_achievements: yes
          plugin_achievements_display: compact
          token: ${{ secrets.METRICS_TOKEN }}

      - name: 🐈‍⬛ Rihgt
        uses: ./
        with:
          config_order: spotify, steam
          filename: assets/right.svg
          base: ''
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_played_at: yes
          plugin_music_playlist: https://open.spotify.com/embed/playlist/09JBXDWkfQM56skfsMdLCz?utm_source=generator
          plugin_music_provider: spotify
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: tardis
          
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_achievements_limit: 1
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: '746951424'
          
          token: ${{ secrets.METRICS_TOKEN }}
          
      
